CARGO_VERSION := $(shell cargo version 2>/dev/null)

.PHONY: package
package:
	substreams pack substreams.yaml

.PHONY: run
run: package
	substreams run substreams.yaml $(if $(MODULE),$(MODULE),{{ .ModuleName }} $(if $(START_BLOCK),-s $(START_BLOCK)) $(if $(STOP_BLOCK),-t $(STOP_BLOCK))

.PHONY: gui
gui: package
	substreams gui substreams.yaml $(if $(MODULE),$(MODULE),{{ .ModuleName }} $(if $(START_BLOCK),-s $(START_BLOCK)) $(if $(STOP_BLOCK),-t $(STOP_BLOCK))
