[package]
name = "my_project"
version = "0.0.1"
edition = "2021"

[lib]
name = "substreams"
crate-type = ["cdylib"]

[dependencies]
hex-literal = "1.1.0"
num-bigint = "0.5"
num-traits = "0.2.15"
prost = "0.14"
prost-types = "0.14"
substreams = "0.7"
substreams-solana = "0.15"
substreams-solana-program-instructions = "0.3"
substreams-database-change = "3"
substreams-entity-change = "2"
anchor-lang = ">=0.30.1"
sologger_log_context = "0.2.4"
base64 = "0.23.0"

# Required so that ethabi > ethereum-types build correctly under wasm32-unknown-unknown
[target.wasm32-unknown-unknown.dependencies]
getrandom = { version = "0.2", features = ["custom"] }

[build-dependencies]
anyhow = "1"
regex = "1.8"

[profile.release]
lto = true
opt-level = 's'
strip = "debuginfo"
