// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package codegen

import (
	"fmt"
	"strings"
)

const (
	// SubstreamsSinkChoiceNone is a SubstreamsSinkChoice of type none.
	SubstreamsSinkChoiceNone SubstreamsSinkChoice = "none"
	// SubstreamsSinkChoicePostgres is a SubstreamsSinkChoice of type postgres.
	SubstreamsSinkChoicePostgres SubstreamsSinkChoice = "postgres"
	// SubstreamsSinkChoiceClickhouse is a SubstreamsSinkChoice of type clickhouse.
	SubstreamsSinkChoiceClickhouse SubstreamsSinkChoice = "clickhouse"
	// SubstreamsSinkChoiceParquet is a SubstreamsSinkChoice of type parquet.
	SubstreamsSinkChoiceParquet SubstreamsSinkChoice = "parquet"
	// SubstreamsSinkChoiceGolang is a SubstreamsSinkChoice of type golang.
	SubstreamsSinkChoiceGolang SubstreamsSinkChoice = "golang"
	// SubstreamsSinkChoiceRust is a SubstreamsSinkChoice of type rust.
	SubstreamsSinkChoiceRust SubstreamsSinkChoice = "rust"
	// SubstreamsSinkChoiceJavascript is a SubstreamsSinkChoice of type javascript.
	SubstreamsSinkChoiceJavascript SubstreamsSinkChoice = "javascript"
	// SubstreamsSinkChoicePython is a SubstreamsSinkChoice of type python.
	SubstreamsSinkChoicePython SubstreamsSinkChoice = "python"
)

var ErrInvalidSubstreamsSinkChoice = fmt.Errorf("not a valid SubstreamsSinkChoice, try [%s]", strings.Join(_SubstreamsSinkChoiceNames, ", "))

var _SubstreamsSinkChoiceNames = []string{
	string(SubstreamsSinkChoiceNone),
	string(SubstreamsSinkChoicePostgres),
	string(SubstreamsSinkChoiceClickhouse),
	string(SubstreamsSinkChoiceParquet),
	string(SubstreamsSinkChoiceGolang),
	string(SubstreamsSinkChoiceRust),
	string(SubstreamsSinkChoiceJavascript),
	string(SubstreamsSinkChoicePython),
}

// SubstreamsSinkChoiceNames returns a list of possible string values of SubstreamsSinkChoice.
func SubstreamsSinkChoiceNames() []string {
	tmp := make([]string, len(_SubstreamsSinkChoiceNames))
	copy(tmp, _SubstreamsSinkChoiceNames)
	return tmp
}

// SubstreamsSinkChoiceValues returns a list of the values for SubstreamsSinkChoice
func SubstreamsSinkChoiceValues() []SubstreamsSinkChoice {
	return []SubstreamsSinkChoice{
		SubstreamsSinkChoiceNone,
		SubstreamsSinkChoicePostgres,
		SubstreamsSinkChoiceClickhouse,
		SubstreamsSinkChoiceParquet,
		SubstreamsSinkChoiceGolang,
		SubstreamsSinkChoiceRust,
		SubstreamsSinkChoiceJavascript,
		SubstreamsSinkChoicePython,
	}
}

// String implements the Stringer interface.
func (x SubstreamsSinkChoice) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x SubstreamsSinkChoice) IsValid() bool {
	_, err := ParseSubstreamsSinkChoice(string(x))
	return err == nil
}

var _SubstreamsSinkChoiceValue = map[string]SubstreamsSinkChoice{
	"none":       SubstreamsSinkChoiceNone,
	"postgres":   SubstreamsSinkChoicePostgres,
	"clickhouse": SubstreamsSinkChoiceClickhouse,
	"parquet":    SubstreamsSinkChoiceParquet,
	"golang":     SubstreamsSinkChoiceGolang,
	"rust":       SubstreamsSinkChoiceRust,
	"javascript": SubstreamsSinkChoiceJavascript,
	"python":     SubstreamsSinkChoicePython,
}

// ParseSubstreamsSinkChoice attempts to convert a string to a SubstreamsSinkChoice.
func ParseSubstreamsSinkChoice(name string) (SubstreamsSinkChoice, error) {
	if x, ok := _SubstreamsSinkChoiceValue[name]; ok {
		return x, nil
	}
	return SubstreamsSinkChoice(""), fmt.Errorf("%s is %w", name, ErrInvalidSubstreamsSinkChoice)
}

// MarshalText implements the text marshaller method.
func (x SubstreamsSinkChoice) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *SubstreamsSinkChoice) UnmarshalText(text []byte) error {
	tmp, err := ParseSubstreamsSinkChoice(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
