// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: sf/codegen/remotebuild/v1/remotebuild.proto

package pbbuild

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Zip file with source code to unzip in a temporary directory.
	SourceCode []byte `protobuf:"bytes,1,opt,name=source_code,json=sourceCode,proto3" json:"source_code,omitempty"`
	// Environment vars, passed to `exec.Command()`
	Env []string `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty"`
	// Double star glob pattern to collect after the build has succeeded
	CollectPattern string `protobuf:"bytes,3,opt,name=collect_pattern,json=collectPattern,proto3" json:"collect_pattern,omitempty"`
	// Subfolder of source_code zip file to cd into before running the build
	Subfolder     string `protobuf:"bytes,4,opt,name=subfolder,proto3" json:"subfolder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildRequest) Reset() {
	*x = BuildRequest{}
	mi := &file_sf_codegen_remotebuild_v1_remotebuild_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRequest) ProtoMessage() {}

func (x *BuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_codegen_remotebuild_v1_remotebuild_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRequest.ProtoReflect.Descriptor instead.
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return file_sf_codegen_remotebuild_v1_remotebuild_proto_rawDescGZIP(), []int{0}
}

func (x *BuildRequest) GetSourceCode() []byte {
	if x != nil {
		return x.SourceCode
	}
	return nil
}

func (x *BuildRequest) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *BuildRequest) GetCollectPattern() string {
	if x != nil {
		return x.CollectPattern
	}
	return ""
}

func (x *BuildRequest) GetSubfolder() string {
	if x != nil {
		return x.Subfolder
	}
	return ""
}

type BuildResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Error string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Logs  string                 `protobuf:"bytes,2,opt,name=logs,proto3" json:"logs,omitempty"`
	// Return only the .spkg for the output
	Artifacts     []*BuildResponse_BuildArtifact `protobuf:"bytes,3,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildResponse) Reset() {
	*x = BuildResponse{}
	mi := &file_sf_codegen_remotebuild_v1_remotebuild_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildResponse) ProtoMessage() {}

func (x *BuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sf_codegen_remotebuild_v1_remotebuild_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildResponse.ProtoReflect.Descriptor instead.
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return file_sf_codegen_remotebuild_v1_remotebuild_proto_rawDescGZIP(), []int{1}
}

func (x *BuildResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BuildResponse) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

func (x *BuildResponse) GetArtifacts() []*BuildResponse_BuildArtifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type BuildResponse_BuildArtifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildResponse_BuildArtifact) Reset() {
	*x = BuildResponse_BuildArtifact{}
	mi := &file_sf_codegen_remotebuild_v1_remotebuild_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildResponse_BuildArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildResponse_BuildArtifact) ProtoMessage() {}

func (x *BuildResponse_BuildArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_sf_codegen_remotebuild_v1_remotebuild_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildResponse_BuildArtifact.ProtoReflect.Descriptor instead.
func (*BuildResponse_BuildArtifact) Descriptor() ([]byte, []int) {
	return file_sf_codegen_remotebuild_v1_remotebuild_proto_rawDescGZIP(), []int{1, 0}
}

func (x *BuildResponse_BuildArtifact) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *BuildResponse_BuildArtifact) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_sf_codegen_remotebuild_v1_remotebuild_proto protoreflect.FileDescriptor

const file_sf_codegen_remotebuild_v1_remotebuild_proto_rawDesc = "" +
	"\n" +
	"+sf/codegen/remotebuild/v1/remotebuild.proto\x12\x11sf.remotebuild.v1\"\x88\x01\n" +
	"\fBuildRequest\x12\x1f\n" +
	"\vsource_code\x18\x01 \x01(\fR\n" +
	"sourceCode\x12\x10\n" +
	"\x03env\x18\x02 \x03(\tR\x03env\x12'\n" +
	"\x0fcollect_pattern\x18\x03 \x01(\tR\x0ecollectPattern\x12\x1c\n" +
	"\tsubfolder\x18\x04 \x01(\tR\tsubfolder\"\xce\x01\n" +
	"\rBuildResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x12\n" +
	"\x04logs\x18\x02 \x01(\tR\x04logs\x12L\n" +
	"\tartifacts\x18\x03 \x03(\v2..sf.remotebuild.v1.BuildResponse.BuildArtifactR\tartifacts\x1aE\n" +
	"\rBuildArtifact\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent2\\\n" +
	"\fBuildService\x12L\n" +
	"\x05Build\x12\x1f.sf.remotebuild.v1.BuildRequest\x1a .sf.remotebuild.v1.BuildResponse0\x01BXZVgithub.com/streamingfast/substreams-codegen/remotebuild/pb/sf/remotebuild/v1;pbbuildv1b\x06proto3"

var (
	file_sf_codegen_remotebuild_v1_remotebuild_proto_rawDescOnce sync.Once
	file_sf_codegen_remotebuild_v1_remotebuild_proto_rawDescData []byte
)

func file_sf_codegen_remotebuild_v1_remotebuild_proto_rawDescGZIP() []byte {
	file_sf_codegen_remotebuild_v1_remotebuild_proto_rawDescOnce.Do(func() {
		file_sf_codegen_remotebuild_v1_remotebuild_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_codegen_remotebuild_v1_remotebuild_proto_rawDesc), len(file_sf_codegen_remotebuild_v1_remotebuild_proto_rawDesc)))
	})
	return file_sf_codegen_remotebuild_v1_remotebuild_proto_rawDescData
}

var file_sf_codegen_remotebuild_v1_remotebuild_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sf_codegen_remotebuild_v1_remotebuild_proto_goTypes = []any{
	(*BuildRequest)(nil),                // 0: sf.remotebuild.v1.BuildRequest
	(*BuildResponse)(nil),               // 1: sf.remotebuild.v1.BuildResponse
	(*BuildResponse_BuildArtifact)(nil), // 2: sf.remotebuild.v1.BuildResponse.BuildArtifact
}
var file_sf_codegen_remotebuild_v1_remotebuild_proto_depIdxs = []int32{
	2, // 0: sf.remotebuild.v1.BuildResponse.artifacts:type_name -> sf.remotebuild.v1.BuildResponse.BuildArtifact
	0, // 1: sf.remotebuild.v1.BuildService.Build:input_type -> sf.remotebuild.v1.BuildRequest
	1, // 2: sf.remotebuild.v1.BuildService.Build:output_type -> sf.remotebuild.v1.BuildResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sf_codegen_remotebuild_v1_remotebuild_proto_init() }
func file_sf_codegen_remotebuild_v1_remotebuild_proto_init() {
	if File_sf_codegen_remotebuild_v1_remotebuild_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_codegen_remotebuild_v1_remotebuild_proto_rawDesc), len(file_sf_codegen_remotebuild_v1_remotebuild_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sf_codegen_remotebuild_v1_remotebuild_proto_goTypes,
		DependencyIndexes: file_sf_codegen_remotebuild_v1_remotebuild_proto_depIdxs,
		MessageInfos:      file_sf_codegen_remotebuild_v1_remotebuild_proto_msgTypes,
	}.Build()
	File_sf_codegen_remotebuild_v1_remotebuild_proto = out.File
	file_sf_codegen_remotebuild_v1_remotebuild_proto_goTypes = nil
	file_sf_codegen_remotebuild_v1_remotebuild_proto_depIdxs = nil
}
