CARGO_VERSION := $(shell cargo version 2>/dev/null)

.PHONY: protogen
protogen:
	substreams protogen  --exclude-paths="google/"

.PHONY: build
build: protogen
	cargo build --release --target wasm32-unknown-unknown

.PHONY: package
package: build
	substreams pack substreams.yaml

