#!/usr/bin/env bash

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

active_pid=
binary="$(basename "${BASH_SOURCE[0]}")"

main() {
  set -e

  version="unknown"
  if [[ -f .version ]]; then
    version=`cat .version`
  fi

  pushd "$ROOT" &> /dev/null
    go install -ldflags "-X main.Version=$version" ./cmd/$binary
  popd &> /dev/null

  # Touches a file after compilation, used within Reflex flow to trigger a reload
  if [[ $TOUCH_AFTER_COMPILE != "" ]]; then
    echo "" > "$TOUCH_AFTER_COMPILE"
  fi

  if [[ $KILL_AFTER != "" ]]; then
    "`go env GOPATH`/bin/$binary" "$@" &
    active_pid=$!

    sleep $KILL_AFTER
    kill -s TERM $active_pid &> /dev/null || true
  else
    exec "`go env GOPATH`/bin/$binary" "$@"
  fi
}

main "$@"
