name: Build docker image

on:
  push:
    tags:
      - "*"
    branches:
      - develop
      - feature/*
      - codegen-cmd
      - staging

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      packages: write

    outputs:
      tags: ${{ steps.meta.outputs.tags }}

    steps:
      - name: "Deploy: GitOps running"
        run: |
          curl https://argocd.streamingfast.io/updater/running --oauth2-bearer ${{ secrets.GITOPS_TOKEN }} \
            -d repo=${{ github.repository }} -d run_id=${{ github.run_id }} -d author=${{ github.actor }} -d "ref=${{ github.ref }}"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate docker tags/labels from github build context
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=sha
            type=raw,enable=${{ github.ref == 'refs/heads/develop' }},value=develop
          flavor: |
            latest=${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: "Deploy: trigger GitOps"
        run: |
          curl https://argocd.streamingfast.io/updater/success --oauth2-bearer ${{ secrets.GITOPS_TOKEN }} \
            -d repo=${{ github.repository }} -d run_id=${{ github.run_id }} -d "ref=${{ github.ref }}" \
            -d "author=${{ github.actor }}" -d "images=${{ steps.meta.outputs.tags }}"
      - name: "Deploy: GitOps failed"
        if: ${{ failure() }}
        run: |
          curl https://argocd.streamingfast.io/updater/failed --oauth2-bearer ${{ secrets.GITOPS_TOKEN }} \
            -d repo=${{ github.repository }} -d run_id=${{ github.run_id }}
