name: Integration tests

on:
  push:
    branches:
      - develop
      - codegen-cmd
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    if: "${{ !startsWith(github.event.head_commit.message, 'GitBook: [#') }}"
    strategy:
      matrix:
        go-version: [ 1.21.x ]
        os: [ubuntu-latest, macos-latest]

    env:
      TEST_LOCAL_CODEGEN: "true"
      RUN_INTEGRATION_TESTS: "true"
      CODEGEN_MAINNET_API_KEY: ${{ secrets.CODEGEN_MAINNET_API_KEY }}
      REGISTRY: ghcr.io
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run Tests
        run: go test -v ./...

      - name: Build
        run: go build ./...