name: Integration tests

on:
  push:
    branches:
      - develop
      - codegen-cmd
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: "${{ !startsWith(github.event.head_commit.message, 'GitBook: [#') }}"

    env:
      INTEGRATION_TESTS_IN_DOCKER: "false"
      RUN_INTEGRATION_TESTS: "true"
      CI: "true"
      CODEGEN_MAINNET_API_KEY: ${{ secrets.CODEGEN_MAINNET_API_KEY }}
      REGISTRY: ghcr.io
      BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ">=1.24.0"
          cache: true

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install substreams CLI
        run: |
          curl -L https://github.com/streamingfast/substreams/releases/download/v1.16.6/substreams_linux_x86_64.tar.gz | tar -xz
          sudo mv substreams /usr/local/bin/
          substreams --version

      - name: Install buf CLI
        run: |
          curl -sSL "https://github.com/bufbuild/buf/releases/download/v1.28.1/buf-Linux-x86_64" -o buf
          sudo mv buf /usr/local/bin/
          sudo chmod +x /usr/local/bin/buf
          buf --version

      - name: Run Tests
        run: go test -v ./... -timeout 1800s

      - name: Build
        run: go build ./...
