name: Integration tests

on:
  push:
    branches:
      - develop
      - codegen-cmd
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: "${{ !startsWith(github.event.head_commit.message, 'GitBook: [#') }}"

    env:
      TEST_LOCAL_CODEGEN: "true"
      RUN_INTEGRATION_TESTS: "true"
      CODEGEN_MAINNET_API_KEY: ${{ secrets.CODEGEN_MAINNET_API_KEY }}
      REGISTRY: ghcr.io
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ">=1.23.0"
          cache: true

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests
        run: go test -v ./...

      - name: Build
        run: go build ./...